title: Abhay Saxena
description: "BS-MS Dual Degree Student in Physics at IISER Kolkata. Researching Ultrafast Terahertz Spectroscopy and Spintronics."
url: "https://saxenabhay.github.io"
theme: null
markdown: kramdown
permalink: /:title/

# This helps Google find your pages
plugins:
  - jekyll-sitemap